export type ProductCategory =
  | "vegetables"
  | "fruits"
  | "spices"
  | "nuts"
  | "eggs"
  | "oils";

export type Product = {
  id: string;
  name: string;
 subtitle?: string;   
  category: ProductCategory;
  origin: string;
  type: "Organic" | "Regular";
  unit: string;
  marketAvg: number; // Al Aweer Rate
  myPrice: number; // MyVegMarket Price
  image: string; // primary image
  fallbackImage?: string; // fallback if primary fails
  badgeColor: string;
  about?: string;
   packaging?: string;
  freshness?: string;
};

// Use direct images.unsplash.com URLs (stable, not random like source.unsplash.com)
const FALLBACK_PRODUCE =
  "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1600&q=80";

export const PRODUCTS: Product[] = [
  // ----------------------------
  // VEGETABLES
  // ----------------------------
  {
    id: "tomato-uae",
    name: "Tomato (Local)",
    subtitle: "Fresh Daily Supply • Per KG",
    category: "vegetables",
    origin: "UAE",
    type: "Regular",
    unit: "KG",
    marketAvg: 9.5,
    myPrice: 6.75,
    image:
     "/images/products/vegetables/tomato.jpeg",
    fallbackImage: FALLBACK_PRODUCE,
    badgeColor: "bg-red-600",
    packaging: "10KG Per Bag",
    freshness: "Arrived This Morning",
    about:
      "Fresh local tomatoes with good firmness—ideal for restaurants and daily bulk cooking.",
  },
  {
    id: "cucumber-uae",
    name: "Cucumber (Local)",
    subtitle: "Crisp & Clean • 5kg Carton",
    category: "vegetables",
    origin: "UAE",
    type: "Regular",
    unit: "KG",
    marketAvg: 22,
    myPrice: 18.5,
    image:
      "/images/products/vegetables/cucumber.jpeg",
    fallbackImage: FALLBACK_PRODUCE,
    badgeColor: "bg-green-700",
    packaging: "3KG Per Bag",
    freshness: "Harvested 24h ago",
    about:
      "Crisp cucumbers for salads and juice bars. Clean grading and stable supply.",
  },
  
  {
    id: "carrot-aus",
    name: "Carrot (Australia)",
    subtitle: "Crunchy & Sweet • 10kg Bag",
    category: "vegetables",
    origin: "Australia",
    type: "Regular",
    unit: "KG",
    marketAvg: 38,
    myPrice: 32,
    image:
      "https://images.unsplash.com/photo-1447175008436-054170c2e979?auto=format&fit=crop&w=1600&q=80",
    fallbackImage: FALLBACK_PRODUCE,
    badgeColor: "bg-orange-600",
    packaging: "5KG Per Box",
    freshness: "Chilled Storage",
    about:
      "Premium carrots with consistent crunch—great for salads, juices and soups.",
  },
   {
    id: "drumstick",
    name: "Drumstick (Moringa)",
    subtitle: "Fresh Pods • Per KG",
    category: "vegetables",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 22,
    myPrice: 18,
    image: "/images/products/vegetables/drumstick.png",
    badgeColor: "bg-emerald-700",
    packaging: "3KG Per Bag",
    freshness: "Harvested Recently",
    about: "Fresh drumsticks—ideal for sambar and South Indian cuisine.",
  },
   {
    id: "cluster-beans",
    name: "Cluster Beans (Chikudukaya)",
    subtitle: "Fresh • Per KG",
    category: "vegetables",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 20,
    myPrice: 16.5,
    image: "/images/products/vegetables/chikudukaya.png",
    badgeColor: "bg-green-800",
    packaging: "10KG Per Bag",
    freshness: "Fresh Stock",
    about: "Fresh chikudukaya—popular for stir fry and curries.",
  },
   {
    id: "coconut",
    name: "Coconut",
    subtitle: "Whole • Per Piece",
    category: "vegetables",
    origin: "Sri Lanka",
    type: "Regular",
    unit: "KG",
    marketAvg: 6,
    myPrice: 4.75,
    image: "/images/products/vegetables/cocnut.webp",
    badgeColor: "bg-stone-700",
    packaging: "10KG Per Bag",
    freshness: "New Stock",
    about: "Whole coconuts—good for fresh cooking and catering prep.",
  },
  {
    id: "onion-red-oman",
    name: "Red Onions (Oman)",
    subtitle: "Medium Size • 10kg Bag",
    category: "vegetables",
    origin: "Oman",
    type: "Regular",
    unit: "KG",
    marketAvg: 32,
    myPrice: 26.5,
    image: "/images/products/vegetables/onion.png",
    badgeColor: "bg-red-800",
    packaging: "10KG Per Bag",
    freshness: "Daily Supply",
    about:
      "Stable daily onion supply with consistent sizing—ideal for large kitchens.",
  },
   {
    id: "garlic",
    name: "Garlic",
    subtitle: "Fresh Bulbs • Per KG",
    category: "vegetables",
    origin: "China",
    type: "Regular",
    unit: "KG",
    marketAvg: 18,
    myPrice: 14.5,
    image: "/images/products/vegetables/garlic.png",
    badgeColor: "bg-zinc-700",
    packaging: "5KG Per Bag",
    freshness: "New Stock",
    about: "Clean garlic bulbs—great for restaurants and bulk cooking.",
  },
   {
    id: "ginger",
    name: "Ginger",
    subtitle: "Fresh Roots • Per KG",
    category: "vegetables",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 16,
    myPrice: 12.75,
    image: "/images/products/vegetables/ginger.png",
    badgeColor: "bg-amber-700",
    packaging: "3KG Per Bag",
    freshness: "Fresh Batch",
    about: "Aromatic ginger roots—perfect for tea, marinades, and kitchens.",
  },

  // ----------------------------
  // FRUITS
  // ----------------------------
  // ----------------------------
// FRUITS (LOCAL IMAGES)
// ----------------------------
{
  id: "apple",
  name: "Apple",
  subtitle: "18kg Per Box",
  category: "fruits",
  origin: "Turkey",
  type: "Regular",
  unit: "KG",
  marketAvg: 95,
  myPrice: 86,
  image: "/images/products/fruits/apple.webp",
  badgeColor: "bg-red-600",
  packaging: "18kg Per Box",
  freshness: "Import Batch Today",
  about: "Crisp apples with good shelf life—ideal for hotels and retail.",
},
{
  id: "banana",
  name: "Banana",
  subtitle: "13kg Per Box",
  category: "fruits",
  origin: "Ecuador",
  type: "Regular",
  unit: "KG",
  marketAvg: 62,
  myPrice: 56,
  image: "/images/products/fruits/banana.webp",
  badgeColor: "bg-yellow-500",
  packaging: "13kg Per Box",
  freshness: "Ripening Controlled",
  about: "Consistent bananas—great for smoothie bars, breakfast counters and groceries.",
},
{
  id: "black-grapes",
  name: "Black Grapes",
  subtitle: "4.5kg Per Box",
  category: "fruits",
  origin: "India",
  type: "Regular",
  unit: "KG",
  marketAvg: 80,
  myPrice: 72,
  image: "/images/products/fruits/black-grapes.webp",
  badgeColor: "bg-purple-800",
  packaging: "4.5kg Per Box",
  freshness: "Cold Chain Delivered",
  about: "Sweet black grapes for desserts and fruit platters—handled in cold chain.",
},
{
  id: "green-grapes",
  name: "Green Grapes",
  subtitle: "4.5kg Per Box",
  category: "fruits",
  origin: "India",
  type: "Regular",
  unit: "KG",
  marketAvg: 78,
  myPrice: 69,
  image: "/images/products/fruits/green-grapes.webp",
  badgeColor: "bg-emerald-600",
  packaging: "4.5kg Per Box",
  freshness: "Cold Chain Delivered",
  about: "Seedless green grapes—fresh and premium for hotels & retail packs.",
},
{
  id: "kiwi",
  name: "Kiwi",
  subtitle: "3kg Per Box",
  category: "fruits",
  origin: "New Zealand",
  type: "Regular",
  unit: "KG",
  marketAvg: 95,
  myPrice: 86,
  image: "/images/products/fruits/kiwi.webp",
  badgeColor: "bg-lime-700",
  packaging: "3kg Per Box",
  freshness: "Chilled Import Stock",
  about: "Premium kiwi for fruit salads, garnish and breakfast service.",
},
{
  id: "mango",
  name: "Mango",
  subtitle: "5kg Per Box",
  category: "fruits",
  origin: "India",
  type: "Regular",
  unit: "KG",
  marketAvg: 90,
  myPrice: 82,
  image: "/images/products/fruits/mango.webp",
  badgeColor: "bg-amber-600",
  packaging: "5kg Per Box",
  freshness: "Season Fresh",
  about: "Sweet mangoes—great for juice counters, desserts and catering.",
},
{
  id: "orange",
  name: "Orange",
  subtitle: "15kg Per Box",
  category: "fruits",
  origin: "Egypt",
  type: "Regular",
  unit: "KG",
  marketAvg: 75,
  myPrice: 68,
  image: "/images/products/fruits/orange.webp",
  badgeColor: "bg-orange-600",
  packaging: "15kg Per Box",
  freshness: "Import Batch Today",
  about: "Juice grade oranges—perfect for juice stations and breakfast buffets.",
},
{
  id: "papaya",
  name: "Papaya",
  subtitle: "10kg Per Box",
  category: "fruits",
  origin: "Sri Lanka",
  type: "Regular",
  unit: "KG",
  marketAvg: 70,
  myPrice: 62,
  image: "/images/products/fruits/papaya.webp",
  badgeColor: "bg-orange-500",
  packaging: "10kg Per Box",
  freshness: "Fresh Stock",
  about: "Ripe papaya for fruit bowls, smoothies and dessert counters.",
},
{
  id: "pineapple",
  name: "Pineapple",
  subtitle: "12kg Per Box",
  category: "fruits",
  origin: "Philippines",
  type: "Regular",
  unit: "KG",
  marketAvg: 92,
  myPrice: 84,
  image: "/images/products/fruits/pineapple.webp",
  badgeColor: "bg-yellow-600",
  packaging: "12kg Per Box",
  freshness: "Chilled Import Stock",
  about: "Golden sweet pineapples—ideal for juice and catering.",
},
{
  id: "pomegranate",
  name: "Pomegranate",
  subtitle: "5kg Per Box",
  category: "fruits",
  origin: "India",
  type: "Regular",
  unit: "KG",
  marketAvg: 95,
  myPrice: 86,
  image: "/images/products/fruits/pomegranate.webp",
  badgeColor: "bg-red-700",
  packaging: "5kg Per Box",
  freshness: "Fresh Import Stock",
  about: "Premium pomegranates for juice, garnish and breakfast counters.",
},
{
  id: "strawberry",
  name: "Strawberry",
  subtitle: "2kg Per Box",
  category: "fruits",
  origin: "Egypt",
  type: "Regular",
  unit: "KG",
  marketAvg: 110,
  myPrice: 98,
  image: "/images/products/fruits/strawberry.webp",
  badgeColor: "bg-rose-600",
  packaging: "2kg Per Box",
  freshness: "Chilled Stock",
  about: "Fresh strawberries for desserts, bakeries and premium catering.",
},
{
  id: "watermelon",
  name: "Watermelon",
  subtitle: "10kg Per Piece",
  category: "fruits",
  origin: "UAE",
  type: "Regular",
  unit: "KG",
  marketAvg: 18,
  myPrice: 14,
  image: "/images/products/fruits/watermelon.webp",
  badgeColor: "bg-emerald-700",
  packaging: "10kg Per Piece",
  freshness: "Daily Supply",
  about: "Juicy watermelon—perfect for juice shops and summer promotions.",
},
 
  // ----------------------------
  // EGGS
  // ----------------------------
  // ----------------------------
// EGGS (local images)
// Put images in: public/images/products/eggs/
// - brown-eggs.webp
// - white-eggs.webp
// - quail-eggs.webp
// ----------------------------
{
  id: "eggs-brown-uae",
  name: "Brown Eggs (UAE)",
  subtitle: "30 pcs per Tray",
  category: "eggs",
  origin: "UAE",
  type: "Organic",
  unit: "Tray",
  marketAvg: 19,
  myPrice: 16.5,
  image: "/images/products/eggs/brown-eggs.webp",
  badgeColor: "bg-neutral-700",
  packaging: "30 pcs Tray",
  freshness: "Collected Today",
  about:
    "Locally sourced brown eggs—ideal for bakeries, cafes and breakfast operations.",
},
{
  id: "white-eggs-uae",
  name: "White Eggs (UAE)",
  subtitle: "30 pcs per Tray",
  category: "eggs",
  origin: "UAE",
  type: "Regular",
  unit: "Tray",
  marketAvg: 18,
  myPrice: 15.5,
  image: "/images/products/eggs/white-eggs.webp",
  badgeColor: "bg-neutral-700",
  packaging: "30 pcs Tray",
  freshness: "Daily Delivery",
  about:
    "Clean white eggs with stable daily supply—best for restaurants and supermarkets.",
},
{
  id: "quail-eggs-uae",
  name: "Quail Eggs",
  subtitle: "24 pcs per Pack",
  category: "eggs",
  origin: "UAE",
  type: "Regular",
  unit: "Pack",
  marketAvg: 28,
  myPrice: 24,
  image: "/images/products/eggs/quail-eggs.webp",
  badgeColor: "bg-zinc-800",
  packaging: "24 pcs Pack",
  freshness: "Chilled Stock",
  about:
    "Popular for gourmet plating and premium catering—packed clean and delivered chilled.",
},

  // ----------------------------
  // SPICES
  // ----------------------------
  // ----------------------------
  // SPICES  (LOCAL IMAGES + DUMMY RATES)
  // ----------------------------
  {
    id: "bay-leaves",
    name: "Bay Leaves",
    subtitle: "1kg Per Pack",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 18.0,
    myPrice: 16.5,
    image: "/images/products/spices/bay-leaves.webp",
    badgeColor: "bg-green-700",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Clean bay leaves for rice dishes, curries and soups—ideal for bulk kitchens.",
  },
  {
    id: "black-mustard-seeds",
    name: "Black Mustard Seeds",
    subtitle: "5kg Per Box",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 12.5,
    myPrice: 11.5,
    image: "/images/products/spices/black-mustard-seeds.webp",
    badgeColor: "bg-neutral-800",
    packaging: "5kg Box",
    freshness: "Sealed Pack",
    about: "Aromatic mustard seeds for tempering and masala blends—restaurant grade.",
  },
  {
    id: "black-pepper",
    name: "Black Pepper (Whole)",
    subtitle: "5kg Per Box",
    category: "spices",
    origin: "Vietnam",
    type: "Regular",
    unit: "KG",
    marketAvg: 58.0,
    myPrice: 53.5,
    image: "/images/products/spices/black-pepper.webp",
    badgeColor: "bg-neutral-900",
    packaging: "5kg Box",
    freshness: "Sealed Pack",
    about: "Whole peppercorns with strong aroma—perfect for grinders and bulk kitchens.",
  },
  {
    id: "cardamom",
    name: "Cardamom (Green)",
    subtitle: "1kg Per Pack",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 95.0,
    myPrice: 88.0,
    image: "/images/products/spices/cardamom.webp",
    badgeColor: "bg-emerald-700",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Premium green cardamom—ideal for tea, desserts and masala blends.",
  },
  {
    id: "cinnamon-sticks",
    name: "Cinnamon Sticks",
    subtitle: "5kg Per Box",
    category: "spices",
    origin: "Sri Lanka",
    type: "Regular",
    unit: "KG",
    marketAvg: 28.0,
    myPrice: 25.5,
    image: "/images/products/spices/cinnamon-sticks.webp",
    badgeColor: "bg-orange-700",
    packaging: "5kg Box",
    freshness: "Sealed Pack",
    about: "Premium cinnamon sticks—perfect for desserts, beverages and aroma-rich cooking.",
  },
  {
    id: "clove",
    name: "Clove",
    subtitle: "5kg Per Box",
    category: "spices",
    origin: "Indonesia",
    type: "Regular",
    unit: "KG",
    marketAvg: 42.0,
    myPrice: 38.5,
    image: "/images/products/spices/clove.webp",
    badgeColor: "bg-amber-800",
    packaging: "5kg Box",
    freshness: "Sealed Pack",
    about: "Whole clove buds—great for biryani, tea and spice mixes.",
  },
  {
    id: "coriander-seeds",
    name: "Coriander Seeds",
    subtitle: "10kg Per Box",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 10.0,
    myPrice: 9.2,
    image: "/images/products/spices/coriander-seeds.webp",
    badgeColor: "bg-lime-700",
    packaging: "10kg Box",
    freshness: "Sealed Pack",
    about: "High quality coriander seeds for grinding and bulk masala production.",
  },
  {
    id: "cumin",
    name: "Cumin Seeds",
    subtitle: "10kg Per Box",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 22.0,
    myPrice: 20.0,
    image: "/images/products/spices/cumin.webp",
    badgeColor: "bg-yellow-900",
    packaging: "10kg Box",
    freshness: "Sealed Pack",
    about: "Strong aroma cumin seeds—perfect for curry bases and bulk seasoning.",
  },
  {
    id: "fennel-seeds",
    name: "Fennel Seeds",
    subtitle: "10kg Per Box",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 16.0,
    myPrice: 14.8,
    image: "/images/products/spices/fennel-seeds.webp",
    badgeColor: "bg-green-700",
    packaging: "10kg Box",
    freshness: "Sealed Pack",
    about: "Sweet fennel seeds for spice mixes, mouth freshener packs and bulk kitchens.",
  },
  {
    id: "garam-masala",
    name: "Garam Masala",
    subtitle: "5kg Per Box",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 26.0,
    myPrice: 24.0,
    image: "/images/products/spices/garam-masala.webp",
    badgeColor: "bg-amber-700",
    packaging: "5kg Box",
    freshness: "Sealed Pack",
    about: "Restaurant blend garam masala—ideal for curries and bulk cooking.",
  },
  {
    id: "red-chilli-powder",
    name: "Red Chilli Powder",
    subtitle: "5kg Per Box",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 18.5,
    myPrice: 17.0,
    image: "/images/products/spices/red-chilli-powder.webp",
    badgeColor: "bg-red-700",
    packaging: "5kg Box",
    freshness: "Sealed Pack",
    about: "Bright color chilli powder—perfect for marinades, curries and bulk kitchens.",
  },
  {
    id: "saffron",
    name: "Saffron",
    subtitle: "1kg Per Pack",
    category: "spices",
    origin: "Iran",
    type: "Regular",
    unit: "KG",
    marketAvg: 520.0,
    myPrice: 485.0,
    image: "/images/products/spices/saffron.webp",
    badgeColor: "bg-yellow-600",
    packaging: "1kg Pack",
    freshness: "Sealed Pack",
    about: "Premium saffron strands for biryani, desserts and hotel-grade recipes.",
  },
  {
    id: "star-anise",
    name: "Star Anise",
    subtitle: "5kg Per Box",
    category: "spices",
    origin: "China",
    type: "Regular",
    unit: "KG",
    marketAvg: 34.0,
    myPrice: 31.0,
    image: "/images/products/spices/star-anise.webp",
    badgeColor: "bg-yellow-900",
    packaging: "5kg Box",
    freshness: "Sealed Pack",
    about: "Strong aroma—ideal for biryani masala and premium spice blends.",
  },
  {
    id: "turmeric-roots",
    name: "Turmeric Roots",
    subtitle: "10kg Per Box",
    category: "spices",
    origin: "India",
    type: "Regular",
    unit: "KG",
    marketAvg: 9.5,
    myPrice: 8.8,
    image: "/images/products/spices/turmeric-roots.webp",
    badgeColor: "bg-amber-600",
    packaging: "10kg Box",
    freshness: "Fresh Stock",
    about: "Fresh turmeric roots for grinding and bulk kitchen prep.",
  },

  
  // ----------------------------
  // NUTS (important: use DRY FRUITS / MIXED NUTS visuals)
  // ----------------------------
    // ----------------------------
  // NUTS & DRY FRUITS (LOCAL IMAGES + DUMMY RATES)
  // ----------------------------
  {
    id: "cashew",
    name: "Cashew Nuts",
    subtitle: "10kg Per Box",
    category: "nuts",
    origin: "Vietnam",
    type: "Regular",
    unit: "KG",
    marketAvg: 46.0,
    myPrice: 42.5,
    image: "/images/products/nuts/cashew.webp",
    badgeColor: "bg-amber-600",
    packaging: "10kg Box",
    freshness: "Sealed Box",
    about: "Whole premium cashews for sweets, snacks and bulk kitchen use.",
  },
  {
    id: "almond",
    name: "Almond",
    subtitle: "10kg Per Box",
    category: "nuts",
    origin: "USA",
    type: "Regular",
    unit: "KG",
    marketAvg: 44.0,
    myPrice: 40.8,
    image: "/images/products/nuts/almond.webp",
    badgeColor: "bg-rose-700",
    packaging: "10kg Box",
    freshness: "Sealed Box",
    about: "Crunchy almonds for bakeries, cafes and retail packing.",
  },
  {
    id: "walnut",
    name: "Walnut (Shelled)",
    subtitle: "10kg Per Box",
    category: "nuts",
    origin: "Chile",
    type: "Regular",
    unit: "KG",
    marketAvg: 48.0,
    myPrice: 44.0,
    image: "/images/products/nuts/walnut.webp",
    badgeColor: "bg-stone-700",
    packaging: "10kg Box",
    freshness: "Sealed Box",
    about: "Premium shelled walnuts—perfect for desserts, salads and healthy mixes.",
  },
  {
    id: "pista",
    name: "Pistachio",
    subtitle: "10kg Per Box",
    category: "nuts",
    origin: "Iran",
    type: "Regular",
    unit: "KG",
    marketAvg: 64.0,
    myPrice: 59.0,
    image: "/images/products/nuts/pista.webp",
    badgeColor: "bg-lime-700",
    packaging: "10kg Box",
    freshness: "Sealed Box",
    about: "Premium pistachios for sweets, ice cream, bakeries and retail packs.",
  },
  {
    id: "raisins",
    name: "Dry Grapes (Raisins)",
    subtitle: "5kg Per Box",
    category: "nuts",
    origin: "Turkey",
    type: "Regular",
    unit: "KG",
    marketAvg: 18.0,
    myPrice: 16.6,
    image: "/images/products/nuts/raisins.webp",
    badgeColor: "bg-yellow-700",
    packaging: "5kg Box",
    freshness: "Sealed Box",
    about: "Golden raisins for bakeries, desserts and bulk mixes.",
  },
  {
    id: "dates",
    name: "Dates",
    subtitle: "5kg Per Box",
    category: "nuts",
    origin: "UAE",
    type: "Regular",
    unit: "KG",
    marketAvg: 22.0,
    myPrice: 20.0,
    image: "/images/products/nuts/dates.webp",
    badgeColor: "bg-amber-800",
    packaging: "5kg Box",
    freshness: "Packed Fresh",
    about: "Soft premium dates for retail, gifting and hotel breakfast service.",
  },
{
  id: "mixed-nuts",
  name: "Mixed Nuts & Dry Fruits",
  subtitle: "5kg Per Box",
  category: "nuts",
  origin: "UAE",
  type: "Regular",
  unit: "KG",
  marketAvg: 32.0,
  myPrice: 29.5,
  image: "/images/products/nuts/mixed-nuts.webp",
  badgeColor: "bg-emerald-700",
  packaging: "5kg Box",
  freshness: "Packed Fresh",
  about: "Premium dry fruits mix for retail packs, gifting and catering supply.",
},


  // ----------------------------
  // OILS
  // ----------------------------
  // ----------------------------
// OILS (local images)
// Put images in: public/images/products/oils/
// - olive-oil.webp
// - sunflower-oil.webp
// - groundnut-oil.webp
// - sesame-oil.webp
// ----------------------------
{
  id: "olive-oil",
  name: "Olive Oil",
  subtitle: "5L per Tin",
  category: "oils",
  origin: "Spain",
  type: "Regular",
  unit: "Bottle",
  marketAvg: 110,
  myPrice: 98,
  image: "/images/products/oils/olive-oil.webp",
  badgeColor: "bg-green-700",
  packaging: "5L Tin",
  freshness: "Sealed Pack",
  about: "Premium olive oil for salads, cooking and HORECA supply.",
},
{
  id: "sunflower-oil",
  name: "Sunflower Oil",
  subtitle: "5L per Tin",
  category: "oils",
  origin: "Ukraine",
  type: "Regular",
  unit: "Bottle",
  marketAvg: 55,
  myPrice: 49,
  image: "/images/products/oils/sunflower-oil.webp",
  badgeColor: "bg-yellow-600",
  packaging: "5L Bottle",
  freshness: "Sealed Pack",
  about: "Everyday cooking oil for restaurants and bulk kitchens.",
},
{
  id: "groundnut-oil",
  name: "Groundnut Oil",
  subtitle: "5L per Tin",
  category: "oils",
  origin: "India",
  type: "Regular",
  unit: "Bottle",
  marketAvg: 75,
  myPrice: 68,
  image: "/images/products/oils/groundnut-oil.webp",
  badgeColor: "bg-orange-700",
  packaging: "5L Bottle",
  freshness: "Sealed Pack",
  about: "Good for frying and high-heat cooking with a clean taste.",
},
{
  id: "sesame-oil",
  name: "Sesame Oil",
  subtitle: "1L per Bottle",
  category: "oils",
  origin: "India",
  type: "Regular",
  unit: "Bottle",
  marketAvg: 34,
  myPrice: 29,
  image: "/images/products/oils/sesame-oil.webp",
  badgeColor: "bg-amber-700",
  packaging: "1L Bottle",
  freshness: "Sealed Pack",
  about: "Aromatic sesame oil—best for flavor-rich cooking and marinades.",
},
];